/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewTubes;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Martcel
 */

public class Login2 extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    
   
    public Login2() {
        initComponents();
    }

    public JButton getDosen() {
        return Dosen;
    }

    public JButton getMahasiswa() {
        return Mahasiswa;
    }
    public void addListener(ActionListener e){
        Dosen.addActionListener(e);
        Mahasiswa.addActionListener(e);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dosen = new javax.swing.JButton();
        Mahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dosen.setText("Dosen");

        Mahasiswa.setText("Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Dosen)
                .addGap(79, 79, 79)
                .addComponent(Mahasiswa)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosen)
                    .addComponent(Mahasiswa))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dosen;
    private javax.swing.JButton Mahasiswa;
    // End of variables declaration//GEN-END:variables
}
